### ISSUE TITLE
What's  the difference bewteen FaceParsingNet18 and EHANet18?

### ISSUE THREAD

**Issue by zyainfal** [JACKYLUO1991/FaceParsing#10]
Hi, I'm trying to train a facial segmentation network based on your code, and I find that FaceParsingNet18 and EHANet18 have almost the same architecture and forwarding function. Is this a miss you made during the code revision?

**Comment by zyainfal** [comment]
OK, I see the difference, I will try to reproduce your results

**Comment by Danbinabo** [comment]
Hi,Can you run this code for train in CelebAMask-HQ dataset? I have some question for you,can you provide connection ways?(qq?or email),thank you.

**Comment by zyainfal** [comment]
> Hi,Can you run this code for train in CelebAMask-HQ dataset? I have some question for you,can you provide connection ways?(qq?or email),thank you.

Hi, I'm just busy recently. So I would love to tell you how to prepare data and training.

For data preparation, you can follow `https://github.com/switchablenorms/CelebAMask-HQ/tree/master/face_parsing/Data_preprocessing` with CelebMaskHQ dataset downloaded.

And for training is quite easy. 
You only need to modify the data path. FYI, you may use faceparsingnet18/34 instead of ehanet18/34. The structures of them are almost the same, but faceparsingnet works better a little. 
Also, you may need more data augmentations for better performance. The augmentations used in the original code is too simple.

And I'm training the model by some personal modifications, here is what I get from faceparsingnet18 (please ignore that I'm using train/val split to train and verify the model by test split)
![捕获](https://user-images.githubusercontent.com/28991072/82110684-d727d800-9772-11ea-9a67-052490e632c0.PNG)

**Comment by zyainfal** [comment]
@Danbinabo

**Comment by Danbinabo** [comment]
For train when run main.py&nbsp; prompt :from inplace_abn import InPlaceABN&nbsp; # replace is ok!
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;ModuleNotFoundError: No module named 'inplace_abn',
This is a lack of modules inplace_abn.py? hao to solver it? thank you.
Is this a lack of modules?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Yuhao"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月16日(星期六) 中午12:47
收件人:&nbsp;"JACKYLUO1991/FaceParsing"<FaceParsing@noreply.github.com&gt;;
抄送:&nbsp;"丹兵"<994329541@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [JACKYLUO1991/FaceParsing] What's  the difference bewteen FaceParsingNet18 and EHANet18? (#10)





  
Hi,Can you run this code for train in CelebAMask-HQ dataset? I have some question for you,can you provide connection ways?(qq?or email),thank you.
  
Hi, I'm just busy recently. So I would love to tell you how to prepare data and training.
 
For data preparation, you can follow https://github.com/switchablenorms/CelebAMask-HQ/tree/master/face_parsing/Data_preprocessing with CelebMaskHQ dataset downloaded.
 
And for training is quite easy.
 You only need to modify the data path. FYI, you may use faceparsingnet18/34 instead of ehanet18/34. The structures of them are almost the same, but faceparsingnet works better a little.
 Also, you may need more data augmentations for better performance. The augmentations used in the original code is too simple.
 
And I'm training the model by some personal modifications, here is what I get from faceparsingnet18 (please ignore that I'm using train/val split to train and verify the model by test split)

**Comment by Danbinabo** [comment]
For train when run main.py&nbsp; prompt :from inplace_abn import InPlaceABN&nbsp; # replace is ok!
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;ModuleNotFoundError: No module named 'inplace_abn'.(in ce2p.py)&nbsp;
This is a lack of modules inplace_abn.py? hao to solver it? thank you.




------------------ 原始邮件 ------------------
发件人:&nbsp;"Yuhao"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月16日(星期六) 中午12:47
收件人:&nbsp;"JACKYLUO1991/FaceParsing"<FaceParsing@noreply.github.com&gt;;
抄送:&nbsp;"丹兵"<994329541@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [JACKYLUO1991/FaceParsing] What's  the difference bewteen FaceParsingNet18 and EHANet18? (#10)





  
Hi,Can you run this code for train in CelebAMask-HQ dataset? I have some question for you,can you provide connection ways?(qq?or email),thank you.
  
Hi, I'm just busy recently. So I would love to tell you how to prepare data and training.
 
For data preparation, you can follow https://github.com/switchablenorms/CelebAMask-HQ/tree/master/face_parsing/Data_preprocessing with CelebMaskHQ dataset downloaded.
 
And for training is quite easy.
 You only need to modify the data path. FYI, you may use faceparsingnet18/34 instead of ehanet18/34. The structures of them are almost the same, but faceparsingnet works better a little.
 Also, you may need more data augmentations for better performance. The augmentations used in the original code is too simple.
 
And I'm training the model by some personal modifications, here is what I get from faceparsingnet18 (please ignore that I'm using train/val split to train and verify the model by test split)

**Comment by zyainfal** [comment]
@Danbinabo 
This module is used for ce2p, which means you can just comment it out in case you are not going to train a ce2p model.
If you need that model, you can search it on github since I think it is copied by the author from somewhere with keyword 'ce2p'.

**Comment by JACKYLUO1991** [comment]
@zyainfal @Danbinabo Indeed, I copied the code from the 2018 Human parsing Champion.

**Comment by leon-liangwu** [comment]
> > Hi,Can you run this code for train in CelebAMask-HQ dataset? I have some question for you,can you provide connection ways?(qq?or email),thank you.
> 
> Hi, I'm just busy recently. So I would love to tell you how to prepare data and training.
> 
> For data preparation, you can follow `https://github.com/switchablenorms/CelebAMask-HQ/tree/master/face_parsing/Data_preprocessing` with CelebMaskHQ dataset downloaded.
> 
> And for training is quite easy.
> You only need to modify the data path. FYI, you may use faceparsingnet18/34 instead of ehanet18/34. The structures of them are almost the same, but faceparsingnet works better a little.
> Also, you may need more data augmentations for better performance. The augmentations used in the original code is too simple.
> 
> And I'm training the model by some personal modifications, here is what I get from faceparsingnet18 (please ignore that I'm using train/val split to train and verify the model by test split)
> ![捕获](https://user-images.githubusercontent.com/28991072/82110684-d727d800-9772-11ea-9a67-052490e632c0.PNG)

> > Hi,Can you run this code for train in CelebAMask-HQ dataset? I have some question for you,can you provide connection ways?(qq?or email),thank you.
> 
> Hi, I'm just busy recently. So I would love to tell you how to prepare data and training.
> 
> For data preparation, you can follow `https://github.com/switchablenorms/CelebAMask-HQ/tree/master/face_parsing/Data_preprocessing` with CelebMaskHQ dataset downloaded.
> 
> And for training is quite easy.
> You only need to modify the data path. FYI, you may use faceparsingnet18/34 instead of ehanet18/34. The structures of them are almost the same, but faceparsingnet works better a little.
> Also, you may need more data augmentations for better performance. The augmentations used in the original code is too simple.
> 
> And I'm training the model by some personal modifications, here is what I get from faceparsingnet18 (please ignore that I'm using train/val split to train and verify the model by test split)
> ![捕获](https://user-images.githubusercontent.com/28991072/82110684-d727d800-9772-11ea-9a67-052490e632c0.PNG)

Is this the performance on validation dataset or testing dataset?
